<?php

namespace AppBundle\Repository;

/**
 * ToyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToyRepository extends \Doctrine\ORM\EntityRepository
{
}
